In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./datasetes/credit/creditcard.csv", low_memory=False)
# df = pd.read_csv('creditcard.csv', low_memory=False)
df = df.sample(frac=1, random_state=1).reset_index(drop=True)
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0  119907.0 -0.611712 -0.769705 -0.149759 -0.224877  2.028577 -2.019887   
1   78340.0 -0.814682  1.319219  1.329415  0.027273 -0.284871 -0.653985   
2   82382.0 -0.318193  1.118618  0.969864 -0.127052  0.569563 -0.532484   
3   31717.0 -1.328271  1.018378  1.775426 -1.574193 -0.117696 -0.457733   
4   80923.0  1.276712  0.617120 -0.578014  0.879173  0.061706 -1.472002   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.292491 -0.523020  0.358468  ... -0.075208  0.045536  0.380739  0.023440   
1  0.321552  0.435975 -0.704298  ... -0.128619 -0.368565  0.090660  0.401147   
2  0.706252 -0.064966 -0.463271  ... -0.305402 -0.774704 -0.123884 -0.495687   
3  0.681867 -0.031641  0.383872  ... -0.220815 -0.419013 -0.239197  0.009967   
4  0.373692 -0.287204 -0.084482  ... -0.160161 -0.430404 -0.076738  0.258708   

        V25       V26       V27       V28  Amount  Class  
0 -2.220686 -0.201146  0.066501  0.221180    1.79      0  
1 -0.261034  0.080621  0.162427  0.059456    1.98      0  
2 -0.018148  0.121679  0.249050  0.092516    0.89      0  
3  0.232829  0.814177  0.098797 -0.004273   15.98      0  
4  0.552170  0.370701 -0.034255  0.041709    0.76      0  

[5 rows x 31 columns]

【read】:使用pandas读取csv；

【sample】:随机抽取，frac是比例，random_state=1,可以取得重复数据

In [5]:
frauds = df.loc[df['Class'] == 1]
non_frauds = df.loc[df['Class'] == 0]
print("We have", len(frauds), "fraud data points and", len(non_frauds), "nonfraudulent data points.")

We have 492 fraud data points and 284315 nonfraudulent data points.


In [6]:
from sklearn import datasets, linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [10]:
X = df.iloc[:,:-1]
y = df['Class']
print("X and y sizes, respectively:", len(X), len(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=500)
print("Train and test sizes, respectively:", len(X_train), len(y_train), "|", len(X_test), len(y_test))
print("Total number of frauds:", len(y.loc[df['Class'] == 1]), len(y.loc[df['Class'] == 1])/len(y))
print("Number of frauds on y_test:", len(y_test.loc[df['Class'] == 1]), len(y_test.loc[df['Class'] == 1]) / len(y_test))
print("Number of frauds on y_train:", len(y_train.loc[df['Class'] == 1]), len(y_train.loc[df['Class'] == 1])/len(y_train))

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

X and y sizes, respectively: 284807 284807
Train and test sizes, respectively: 185124 185124 | 99683 99683
Total number of frauds: 492 0.001727485630620034
Number of frauds on y_test: 182 0.0018257877471584924
Number of frauds on y_train: 310 0.0016745532724012013


【iloc】:通过行号来取行数据

【train_test_split】：将矩阵随机划分成训练集+测试集。
train_data：被划分的样本特征集
train_target：被划分的样本标签
test_size：如果是浮点数，在0-1之间，表示样本占比；如果是整数的话就是样本的数量
random_state：是随机数的种子。其实就是该组随机数的编号，在需要重复试验的时候，保证得到一组一样的随机数。比如你每次都填1，其他参数一样的情况下你得到的随机数组是一样的。但填0或不填，每次都会不一样。

In [12]:
X_train[0], y_train[0]

(array([ 4.05680000e+04,  1.07986004e+00,  3.74335739e-02,  4.05189660e-01,
         1.11623980e+00, -3.52652667e-01, -4.05465558e-01,  1.48082619e-02,
         1.37820957e-03,  2.03991389e-01, -5.03189566e-02, -2.98616675e-01,
        -1.76794270e-01, -8.90378215e-01,  5.41904085e-01,  1.40271242e+00,
        -4.02862035e-02, -1.52854308e-01, -4.93987693e-01, -7.41539707e-01,
        -1.17354908e-01, -2.28408518e-02, -1.78534699e-01, -8.77119112e-03,
         4.11553535e-02,  3.84051242e-01, -4.37645941e-01,  2.44553934e-02,
         3.11215578e-02,  5.93500000e+01]), 0)

In [13]:
X_test[0], y_test[0]

(array([ 1.52093000e+05,  7.44982141e-03,  1.13163011e+00, -2.66036367e+00,
        -6.75345504e-01,  1.81505622e+00, -5.32755745e-01,  1.19830550e+00,
         4.38943170e-02, -5.81932719e-01, -7.11666890e-02, -5.36796316e-01,
         1.16766819e-01, -7.22340099e-01,  1.37877058e+00, -1.05032091e+00,
        -6.54230796e-01, -5.43860498e-01,  5.89924506e-01,  9.33565770e-01,
        -4.09520114e-01,  5.82155900e-01,  1.66838208e+00, -5.99436990e-02,
        -2.95606238e-01, -1.03082614e+00, -1.61548812e-01, -6.69506565e-02,
         2.40108311e-01,  1.00000000e+00]), 0)

In [14]:
train_pd = pd.DataFrame(X_test, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_test
train_pd.to_csv("./datasetes/credit/credit_test1.csv", index=False)

【train_pd['y']】：直接在train_pd后面加了一列

【to_csv】：写入csv文件

In [15]:
train_pd = pd.DataFrame(X_train, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_train
train_pd.to_csv("./datasetes/credit/credit_train1.csv", index=False)

In [16]:
from sklearn import metrics

def roc_metrix_mult(a, p, labels=[0,1]):
# #     print(p)
#     if len(set(a)) == 1:
# #         return "acc", metrics.accuracy_score(a, p)
#         return "acc", len(a) - len(np.where(a == p)[0])
#     if type(p) == np.float64 or type(p) == float or type(p) == np.int64 or type(p) == int:
    if len(p.shape) == 1:
        print(type(p), p.shape)
        return "roc", metrics.roc_auc_score(a, p)
#     elif len(p[0]) == 2:
    elif len(p.shape) == 2:
        p = [i[1] for i in p]
        return "roc", metrics.roc_auc_score(a, p)
    else:
        print(type(p), p.shape, "error")

In [18]:
import ModelUtils
import importlib
from collections import Counter
import numpy as np
importlib.reload(ModelUtils)

<module 'ModelUtils' from 'C:\\Users\\dxeec\\Desktop\\EcoForest-master\\ModelUtils.py'>

【ModelUtils】：自己写的py文件。各个模型的调用。

In [19]:
%%time
ModelUtils.mlp_classifier(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)

train ('roc', 0.5)
test ('roc', 0.5)
Wall time: 5min 55s


(MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
        beta_2=0.999, early_stopping=False, epsilon=1e-08,
        hidden_layer_sizes=(200, 100, 10), learning_rate='constant',
        learning_rate_init=0.001, max_iter=1000, momentum=0.9,
        n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
        random_state=None, shuffle=True, solver='adam', tol=0.0001,
        validation_fraction=0.1, verbose=False, warm_start=False),
 array([[0.99833081, 0.00166919],
        [0.99833081, 0.00166919],
        [0.99833081, 0.00166919],
        ...,
        [0.99833081, 0.00166919],
        [0.99833081, 0.00166919],
        [0.99833081, 0.00166919]]))

In [20]:
test_1 = np.array([0.9262, 0.9352, 0.9309, 0.8828, 0.9107])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([0.9262, 0.9352, 0.9309, 0.8828, 0.9107]),
 0.019069829574487544,
 0.91716,
 0.9352,
 0.8828)

In [21]:
test_1 = np.array([5.65, 6.18, 7.19, 5.12, 4.25])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([5.65, 6.18, 7.19, 5.12, 4.25]), 0.9888862421937117, 5.678, 7.19, 4.25)

In [22]:
test_1 = np.array([51.65, 62.18, 71.19, 52.12, 53.8])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([51.65, 62.18, 71.19, 52.12, 53.8 ]),
 7.534038492070505,
 58.188,
 71.19,
 51.65)

In [23]:
%%time
ModelUtils.decision_tree(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)

train ('roc', 1.0)
test ('roc', 0.8761173475422578)
Wall time: 14.7 s


(DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features=None, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, presort=False, random_state=None,
             splitter='best'), array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]))

In [24]:
test_1 = np.array([0.8734, 0.8953, 0.8816, 0.8706, 0.8734])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([0.8734, 0.8953, 0.8816, 0.8706, 0.8734]),
 0.009007019484824045,
 0.8788600000000001,
 0.8953,
 0.8706)

In [25]:
test_1 = np.array([16.6, 16.4, 16.4, 16.4, 16.4])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([16.6, 16.4, 16.4, 16.4, 16.4]),
 0.08000000000000114,
 16.439999999999998,
 16.6,
 16.4)

In [26]:
%%time
ModelUtils.random_forest(X_train, y_train, X_test, y_test, n_estimators=4050, feval=roc_metrix_mult,\
                         max_depth=3, min_samples_leaf=1, min_samples_split=2)

start train: 2019-08-13 17:03:47.411823
start test: 2019-08-13 17:22:50.743717
end test: 2019-08-13 17:22:58.283556
test ('roc', 0.9688458319100224)
train ('roc', 1.0)
Wall time: 19min 33s


(RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=4050, n_jobs=-1,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False), array([[1.00000000e+00, 0.00000000e+00],
        [9.99506173e-01, 4.93827160e-04],
        [9.99506173e-01, 4.93827160e-04],
        ...,
        [1.00000000e+00, 0.00000000e+00],
        [1.00000000e+00, 0.00000000e+00],
        [1.00000000e+00, 0.00000000e+00]]))

In [27]:
%%time
ModelUtils.random_forest(X_train, y_train, X_test, y_test, n_estimators=200, feval=roc_metrix_mult,\
                         max_depth=3, min_samples_leaf=1, min_samples_split=2)

start train: 2019-08-13 17:27:39.147887
start test: 2019-08-13 17:28:36.811094
end test: 2019-08-13 17:28:37.238977
test ('roc', 0.9535513807305045)
train ('roc', 1.0)
Wall time: 59.6 s


(RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False), array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]))

In [28]:
test_1 = np.array([0.9480, 0.9479, 0.9509, 0.9509, 0.9563])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([0.948 , 0.9479, 0.9509, 0.9509, 0.9563]),
 0.003050245891727448,
 0.9507999999999999,
 0.9563,
 0.9479)

In [29]:
test_1 = np.array([5*60+22, 5*60+23, 4*60+57, 5*60+2, 5*60+12])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([322, 323, 297, 302, 312]), 10.419213022104884, 311.2, 323, 297)

In [30]:
%%time
ModelUtils.gdbt_model(X_train, y_train, X_test, y_test, n_estimators=2000, feval=roc_metrix_mult)

train ('roc', 0.9777502018594457)
test ('roc', 0.9598434650444178)
Wall time: 16min 38s


(GradientBoostingClassifier(criterion='friedman_mse', init=None,
               learning_rate=0.1, loss='deviance', max_depth=3,
               max_features=None, max_leaf_nodes=None,
               min_impurity_decrease=0.0, min_impurity_split=None,
               min_samples_leaf=1, min_samples_split=2,
               min_weight_fraction_leaf=0.0, n_estimators=2000,
               n_iter_no_change=None, presort='auto', random_state=None,
               subsample=1.0, tol=0.0001, validation_fraction=0.1,
               verbose=0, warm_start=False),
 array([[9.99966476e-01, 3.35244036e-05],
        [9.99947424e-01, 5.25756434e-05],
        [9.99401719e-01, 5.98281096e-04],
        ...,
        [9.99978750e-01, 2.12503223e-05],
        [9.99967719e-01, 3.22813395e-05],
        [9.99944055e-01, 5.59445318e-05]]))

In [32]:
test_1 = np.array([0.9434, 0.94338904982014105, 0.94337596253657385, 0.94338250617835739, 0.94337596253657385])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([0.9434    , 0.94338905, 0.94337596, 0.94338251, 0.94337596]),
 9.061018168500733e-06,
 0.9433846962143292,
 0.9434,
 0.9433759625365739)

In [33]:
test_1 = np.array([2*60+12, 2*60+36, 2*60+30, 2*60+34, 2*60+25])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([132, 156, 150, 154, 145]), 8.56971411425142, 147.4, 156, 132)

In [34]:
%%time
def roc_metrix(a, p):
    return "roc", metrics.roc_auc_score(a, p)
ModelUtils.xgb_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix)

{'objective': 'binary:logistic'}
before train
[0]	train-error:0.000378	valid-error:0.000692	train-roc:0.912797	valid-roc:0.928431
Multiple eval metrics have been passed: 'valid-roc' will be used for early stopping.

Will train until valid-roc hasn't improved in 500 rounds.
[100]	train-error:0	valid-error:0.000461	train-roc:1	valid-roc:0.982731
[200]	train-error:0	valid-error:0.000461	train-roc:1	valid-roc:0.983351
[300]	train-error:0	valid-error:0.000451	train-roc:1	valid-roc:0.983429
[400]	train-error:0	valid-error:0.000441	train-roc:1	valid-roc:0.983811
[500]	train-error:0	valid-error:0.000431	train-roc:1	valid-roc:0.983761
[600]	train-error:0	valid-error:0.000431	train-roc:1	valid-roc:0.983886
Stopping. Best iteration:
[140]	train-error:0	valid-error:0.000451	train-roc:1	valid-roc:0.984089

[2.0731017e-07 6.9206766e-07 8.0152518e-08 ... 5.7067453e-09 1.4301404e-08
 1.0865173e-07]
train ('roc', 1.0)
[1.3080020e-06 1.8599242e-06 5.4165832e-07 ... 8.8922690e-08 4.1900162e-08
 2.6820075

In [35]:
ModelUtils.baseline_1_flod(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(185124, 30)(185124,)
X_valid.shape, y_valid.shape:(99683, 30)(99683,)
    cross_score: 0.99932
    test score ('roc', 0.9699898371997144)
<class 'numpy.ndarray'> (99683,)
train kflod pred: ('roc', 0.8873224367616384)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.8838276809779456)
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.8873224367616384)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=10, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=1024, verbose=0,
            warm_start=False)

In [36]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(123415, 30)(123415,)
X_valid.shape, y_valid.shape:(61709, 30)(61709,)
    cross_score: 0.99938
    test score ('roc', 0.938519724413836)
X_train.shape, y_train.shape:(123416, 30)(123416,)
X_valid.shape, y_valid.shape:(61708, 30)(61708,)
    cross_score: 0.99947
    test score ('roc', 0.9467638571416424)
X_train.shape, y_train.shape:(123417, 30)(123417,)
X_valid.shape, y_valid.shape:(61707, 30)(61707,)
    cross_score: 0.99922
    test score ('roc', 0.9468378251430682)
<class 'numpy.ndarray'> (185124,)
train kflod pred: ('roc', 0.870908222634998)
[0.00666667 0.00666667 0.00666667 ... 0.01333333 0.97333333 0.00666667]
<class 'numpy.ndarray'> (99683,)
test data ('roc', 0.956568634629659)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.9999945106099699)
[0.00666667 0.00666667 0.00666667 ... 0.01333333 0.97333333 0.00666667]
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.956568634629659)
train lr shape:  (185124, 2)


C:\Users\dxeec\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


<class 'numpy.ndarray'> (185124,)
lr train ('roc', 0.8596314271680996)
test lr shape:  (99683, 2)
<class 'numpy.ndarray'> (99683,)
lr test ('roc', 0.8818430064925075)
lr coef_ -0.31261595922601604


[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurit

In [37]:
a = 6
print(type(a))
import numpy as np
type(a) == np.int64

<class 'int'>


False

In [38]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(123415, 30)(123415,)
X_valid.shape, y_valid.shape:(61709, 30)(61709,)
    cross_score: 0.99938
    test score ('roc', 0.938519724413836)
X_train.shape, y_train.shape:(123416, 30)(123416,)
X_valid.shape, y_valid.shape:(61708, 30)(61708,)
    cross_score: 0.99947
    test score ('roc', 0.9467638571416424)
X_train.shape, y_train.shape:(123417, 30)(123417,)
X_valid.shape, y_valid.shape:(61707, 30)(61707,)
    cross_score: 0.99922
    test score ('roc', 0.9468378251430682)
<class 'numpy.ndarray'> (185124,)
train kflod pred: ('roc', 0.870908222634998)
[0.00666667 0.00666667 0.00666667 ... 0.01333333 0.97333333 0.00666667]
<class 'numpy.ndarray'> (99683,)
test data ('roc', 0.956568634629659)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.9999945106099699)
[0.00666667 0.00666667 0.00666667 ... 0.01333333 0.97333333 0.00666667]
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.956568634629659)
train lr shape:  (185124, 2)


C:\Users\dxeec\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


<class 'numpy.ndarray'> (185124,)
lr train ('roc', 0.8596314271680996)
test lr shape:  (99683, 2)
<class 'numpy.ndarray'> (99683,)
lr test ('roc', 0.8818430064925075)
lr coef_ -0.31261595922601604


[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurit