In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./datasetes/credit/creditcard.csv", low_memory=False)
# df = pd.read_csv('creditcard.csv', low_memory=False)
df = df.sample(frac=1, random_state=1).reset_index(drop=True)
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0  119907.0 -0.611712 -0.769705 -0.149759 -0.224877  2.028577 -2.019887   
1   78340.0 -0.814682  1.319219  1.329415  0.027273 -0.284871 -0.653985   
2   82382.0 -0.318193  1.118618  0.969864 -0.127052  0.569563 -0.532484   
3   31717.0 -1.328271  1.018378  1.775426 -1.574193 -0.117696 -0.457733   
4   80923.0  1.276712  0.617120 -0.578014  0.879173  0.061706 -1.472002   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.292491 -0.523020  0.358468  ... -0.075208  0.045536  0.380739  0.023440   
1  0.321552  0.435975 -0.704298  ... -0.128619 -0.368565  0.090660  0.401147   
2  0.706252 -0.064966 -0.463271  ... -0.305402 -0.774704 -0.123884 -0.495687   
3  0.681867 -0.031641  0.383872  ... -0.220815 -0.419013 -0.239197  0.009967   
4  0.373692 -0.287204 -0.084482  ... -0.160161 -0.430404 -0.076738  0.258708   

        V25       V26       V27       V28  Amount  Class  
0 -2.220686 -0.201146  0.066501  0.221180    1.79      0  
1 -0.261034  0.080621  0.162427  0.059456    1.98      0  
2 -0.018148  0.121679  0.249050  0.092516    0.89      0  
3  0.232829  0.814177  0.098797 -0.004273   15.98      0  
4  0.552170  0.370701 -0.034255  0.041709    0.76      0  

[5 rows x 31 columns]

In [3]:
frauds = df.loc[df['Class'] == 1]
non_frauds = df.loc[df['Class'] == 0]
print("We have", len(frauds), "fraud data points and", len(non_frauds), "nonfraudulent data points.")

We have 492 fraud data points and 284315 nonfraudulent data points.


In [4]:
from sklearn import datasets, linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [5]:
X = df.iloc[:,:-1]
y = df['Class']

print("X and y sizes, respectively:", len(X), len(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=501)
print("Train and test sizes, respectively:", len(X_train), len(y_train), "|", len(X_test), len(y_test))
print("Total number of frauds:", len(y.loc[df['Class'] == 1]), len(y.loc[df['Class'] == 1])/len(y))
print("Number of frauds on y_test:", len(y_test.loc[df['Class'] == 1]), len(y_test.loc[df['Class'] == 1]) / len(y_test))
print("Number of frauds on y_train:", len(y_train.loc[df['Class'] == 1]), len(y_train.loc[df['Class'] == 1])/len(y_train))

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

X and y sizes, respectively: 284807 284807
Train and test sizes, respectively: 185124 185124 | 99683 99683
Total number of frauds: 492 0.001727485630620034
Number of frauds on y_test: 177 0.0017756287431156766
Number of frauds on y_train: 315 0.0017015621961496078


In [6]:
X_train[0], y_train[0]

(array([ 1.42781000e+05,  1.98062304e+00, -6.83169518e-01, -1.69195672e+00,
        -6.21688531e-01,  1.72370818e+00,  3.90954410e+00, -1.26591403e+00,
         1.05750165e+00,  1.31559297e+00, -1.44507198e-01, -2.23030234e-01,
         4.96304220e-01, -5.26724436e-02, -1.87162684e-03,  8.93057566e-01,
        -2.93665762e-04, -5.83857996e-01,  7.31430306e-02, -3.55198228e-01,
        -1.63723067e-01,  1.85740200e-01,  6.97046850e-01,  1.67391664e-01,
         7.26109166e-01, -5.64531001e-02, -1.91281667e-01,  6.27993499e-02,
        -4.45834187e-02,  1.00000000e-02]), 0)

In [7]:
X_test[0], y_test[0]

(array([ 6.86450000e+04, -3.13690428e-01,  1.33661063e+00, -3.15172039e-01,
         9.06919544e-01,  1.85994197e-01, -1.03267932e+00,  5.72752018e-01,
         1.87966820e-01, -4.86341702e-01,  1.18744849e-01, -1.11881819e+00,
        -3.83730875e-01, -6.26866506e-01,  8.96234197e-01,  7.45246888e-01,
        -3.05748701e-01, -7.57001295e-02,  1.17736111e-01,  5.28443891e-01,
        -1.26803718e-01,  1.55895662e-01,  4.79596869e-01,  1.10601716e-01,
         1.82450185e-02, -6.57923355e-01, -3.98103910e-01,  1.83962494e-01,
         1.52030399e-01,  2.69000000e+00]), 0)

In [8]:
train_pd = pd.DataFrame(X_test, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_test
train_pd.to_csv("./datasetes/credit/credit_test2.csv", index=False)

In [9]:
train_pd = pd.DataFrame(X_train, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_train
train_pd.to_csv("./datasetes/credit/credit_train2.csv", index=False)

In [10]:
from sklearn import metrics

def roc_metrix_mult(a, p, labels=[0,1]):
# #     print(p)
#     if len(set(a)) == 1:
# #         return "acc", metrics.accuracy_score(a, p)
#         return "acc", len(a) - len(np.where(a == p)[0])
#     if type(p) == np.float64 or type(p) == float or type(p) == np.int64 or type(p) == int:
    if len(p.shape) == 1:
        print(type(p), p.shape)
        return "roc", metrics.roc_auc_score(a, p)
#     elif len(p[0]) == 2:
    elif len(p.shape) == 2:
        p = [i[1] for i in p]
        return "roc", metrics.roc_auc_score(a, p)
    else:
        print(type(p), p.shape, "error")

In [11]:
import ModelUtils
import importlib
from collections import Counter
importlib.reload(ModelUtils)

<module 'ModelUtils' from 'C:\\Users\\dxeec\\Desktop\\EcoForest-master\\ModelUtils.py'>

In [12]:
%%time
ModelUtils.mlp_classifier(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)

train ('roc', 0.5053218994780282)
test ('roc', 0.5062249035659889)
Wall time: 2min 34s


(MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
        beta_2=0.999, early_stopping=False, epsilon=1e-08,
        hidden_layer_sizes=(200, 100, 10), learning_rate='constant',
        learning_rate_init=0.001, max_iter=1000, momentum=0.9,
        n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
        random_state=None, shuffle=True, solver='adam', tol=0.0001,
        validation_fraction=0.1, verbose=False, warm_start=False),
 array([[0.99742038, 0.00257962],
        [0.99742038, 0.00257962],
        [0.99742038, 0.00257962],
        ...,
        [0.99742038, 0.00257962],
        [0.99742038, 0.00257962],
        [0.99742038, 0.00257962]]))

In [32]:
test_1 = np.array([0.8807, 0.8554, 0.8841, 0.7629, 0.8282])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.8807,  0.8554,  0.8841,  0.7629,  0.8282]),
 0.044489486398473964,
 0.84226000000000012,
 0.8841,
 0.76290000000000002)

In [33]:
test_1 = np.array([2.94, 3.9, 4.92, 3.94, 2.99])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 2.94,  3.9 ,  4.92,  3.94,  2.99]),
 0.72944910720351142,
 3.7379999999999995,
 4.9199999999999999,
 2.9399999999999999)

In [38]:
%%time
ModelUtils.decision_tree(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)

train ('roc', 1.0)
test ('roc', 0.85850079619308095)
Wall time: 14.4 s


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [39]:
test_1 = np.array([0.8529, 0.8670, 0.8670, 0.8726, 0.8585])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.8529,  0.867 ,  0.867 ,  0.8726,  0.8585]),
 0.0069945693219811674,
 0.86360000000000015,
 0.87260000000000004,
 0.85289999999999999)

In [40]:
test_1 = np.array([14.5, 14.3, 14.4, 14.3, 14.4])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 14.5,  14.3,  14.4,  14.3,  14.4]),
 0.07483314773547857,
 14.380000000000001,
 14.5,
 14.300000000000001)

In [52]:
%%time
ModelUtils.random_forest(X_train, y_train, X_test, y_test, n_estimators=2000, feval=roc_metrix_mult,\
                         max_depth=3, min_samples_leaf=1, min_samples_split=2)

KeyboardInterrupt: 

In [48]:
test_1 = np.array([0.9636, 0.9495, 0.9608, 0.9640, 0.9609])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.9636,  0.9495,  0.9608,  0.964 ,  0.9609]),
 0.0052985280975002763,
 0.95975999999999995,
 0.96399999999999997,
 0.94950000000000001)

In [49]:
test_1 = np.array([5*60+4, 4*60+49, 5*60+12, 5*60+33, 5*60+20])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([304, 289, 312, 333, 320]),
 14.813507349712964,
 311.60000000000002,
 333,
 289)

In [57]:
%%time
ModelUtils.gdbt_model(X_train, y_train, X_test, y_test, n_estimators=200, feval=roc_metrix_mult)

train ('roc', 0.39996378929872434)
test ('roc', 0.38411924398051805)
Wall time: 5min 9s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=200,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [ ]:
train ('roc', 0.39996378929872434)
test ('roc', 0.38411702965190414)
Wall time: 2min 24s
train ('roc', 0.39996378929872434)
test ('roc', 0.38411850587098012)
Wall time: 3min 27s
train ('roc', 0.87277848507171751)
test ('roc', 0.84720124760951865)
Wall time: 8min 8s
GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=200,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [58]:
test_1 = np.array([0.87277848507171751, 0.87247848507171751, 0.87277848507171751, 0.87277848507171751, 0.87277848507171751])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.87277849,  0.87247849,  0.87277849,  0.87277849,  0.87277849]),
 0.00011999999999998679,
 0.87271848507171745,
 0.87277848507171751,
 0.87247848507171755)

In [57]:
%%time
def roc_metrix(a, p):
    return "roc", metrics.roc_auc_score(a, p)
ModelUtils.xgb_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix)

{'objective': 'binary:logistic'}
before train
[0]	train-roc:0.912797	valid-roc:0.928431
Multiple eval metrics have been passed: 'valid-roc' will be used for early stopping.

Will train until valid-roc hasn't improved in 500 rounds.
[100]	train-roc:1	valid-roc:0.982731
[200]	train-roc:1	valid-roc:0.983351
[300]	train-roc:1	valid-roc:0.983429
[400]	train-roc:1	valid-roc:0.983811
[500]	train-roc:1	valid-roc:0.983761
[600]	train-roc:1	valid-roc:0.983886
Stopping. Best iteration:
[140]	train-roc:1	valid-roc:0.984089

[  2.07310165e-07   6.92067658e-07   8.01525175e-08 ...,   5.70674530e-09
   1.43014036e-08   1.08651733e-07]
train ('roc', 1.0)
[  1.30800197e-06   1.85992417e-06   5.41658324e-07 ...,   8.89226897e-08
   4.19001616e-08   2.68200750e-07]
test ('roc', 0.9839087154792524)
Wall time: 1min 58s


In [50]:
ModelUtils.baseline_1_flod(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(185124, 30)(185124,)
X_valid.shape, y_valid.shape:(99683, 30)(99683,)
    cross_score: 0.99932
    test score ('roc', 0.96999061028819533)
<class 'numpy.ndarray'> (99683,)
train kflod pred: ('roc', 0.88732243676163836)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.88382768097794562)
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.88732243676163836)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=10, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=1024, verbose=0,
            warm_start=False)

In [17]:
ModelUtils.baseline_1_flod(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(185124, 30)(185124,)
X_valid.shape, y_valid.shape:(99683, 30)(99683,)
    cross_score: 0.99945
    test score ('roc', 0.88434784199804484)
train kflod pred: ('roc', 0.88434784199804484)
train pred ('roc', 1.0)
test pred ('roc', 0.88434784199804484)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=1024, verbose=0,
            warm_start=False)

In [54]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(123415, 30)(123415,)
X_valid.shape, y_valid.shape:(61709, 30)(61709,)
    cross_score: 0.99938
    test score ('roc', 0.9385198072447446)
X_train.shape, y_train.shape:(123416, 30)(123416,)
X_valid.shape, y_valid.shape:(61708, 30)(61708,)
    cross_score: 0.99947
    test score ('roc', 0.94676463023012292)
X_train.shape, y_train.shape:(123417, 30)(123417,)
X_valid.shape, y_valid.shape:(61707, 30)(61707,)
    cross_score: 0.99922
    test score ('roc', 0.94683779753276531)
<class 'numpy.ndarray'> (185124,)
train kflod pred: ('roc', 0.87090822263499801)
[ 0.00666667  0.00666667  0.00666667 ...,  0.01333333  0.97333333
  0.00666667]
<class 'numpy.ndarray'> (99683,)
test data ('roc', 0.95657020841692353)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.99999452806431022)
[ 0.00666667  0.00666667  0.00666667 ...,  0.01333333  0.96666667
  0.00666667]
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.9565711747775244)
train lr shape:  (185124, 2)
<class 

[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurit

In [37]:
a = 6
print(type(a))
import numpy as np
type(a) == np.int64

<class 'int'>


False

In [18]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99914
    test score ('roc', 0.88722796616716715)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99927
    test score ('roc', 0.89012818881885403)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99949
    test score ('roc', 0.87857251979787665)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99935
    test score ('roc', 0.88145264396699896)
X_train.shape, y_train.shape:(148100, 30)(148100,)
X_valid.shape, y_valid.shape:(37024, 30)(37024,)
    cross_score: 0.99938
    test score ('roc', 0.88146269320828119)
train kflod pred: ('roc', 0.89650572971137332)
train pred ('roc', 1.0)
test pred ('roc', 0.88146269320828119)
lr train ('roc', 0.8808425707381643)
lr test 

[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
             oob_score=False, random_state=1023, verbose=0,
             warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
             oob_score=False, random_state=1023, verbose=0,
             warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_no