In [1]:
from sklearn import metrics
import numpy as np
from sklearn.preprocessing import LabelEncoder, LabelBinarizer

In [51]:
metrics.log_loss([1,0,0],[0.2,0.3,0.5], labels=[0,1])

0.88642001231092593

In [53]:
metrics.log_loss([1,1,1],[0.2,0.3,0.5], labels=[0,1])

1.1688526324399939

In [5]:
metrics.log_loss([1,0,0],[[0.8,0.2],[0.7,0.3],[0.5,0.5]])

0.88642001231092593

In [4]:
metrics.log_loss([1,0,0],[[0.2,0.8],[0.3,0.7],[0.5,0.5]])

0.70675451206669704

In [50]:
y_true = [1,1,1]
lb = LabelBinarizer()
lb.fit([0,1])
transformed_labels = lb.transform(y_true)
transformed_labels

array([[1],
       [1],
       [1]])

In [46]:
# y_pred = np.array([[0.8,0.2],[0.7,0.3],[0.5,0.5]])
y_pred = np.array([0.2,0.3,0.5])
y_pred = y_pred[:, np.newaxis]
print(y_pred)
y_pred = np.append(1 - y_pred, y_pred, axis=1)
print(y_pred)
y_pred /= y_pred.sum(axis=1)[:, np.newaxis]
y_pred

[[ 0.2]
 [ 0.3]
 [ 0.5]]
[[ 0.8  0.2]
 [ 0.7  0.3]
 [ 0.5  0.5]]


array([[ 0.8,  0.2],
       [ 0.7,  0.3],
       [ 0.5,  0.5]])

In [47]:
-(transformed_labels * np.log(y_pred))

array([[ 0.22314355,  1.60943791],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [43]:
loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)
loss.sum()

1.83258146374831

In [13]:
y_pred = y_pred[:, np.newaxis]
y_pred

array([[[ 0.8,  0.2]],

       [[ 0.7,  0.3]],

       [[ 0.5,  0.5]]])

In [ ]:
loss = -(transformed_labels * np.log(y_pred)).sum(axis=1)

In [2]:
import numpy as np
import scipy
from scipy import stats

In [41]:
a = np.array([1,1,3])
b = np.array([1,0,np.nan])
a/b

c:\program files\python36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([  1.,  inf,  nan])

In [44]:
c = np.array([  1.,  np.inf,  np.nan])
c[np.isnan(c)] = 0
c

array([  1.,  inf,   0.])

In [49]:
x = np.array([-np.inf, 0., np.inf])
any(~np.isfinite(x))

True

In [50]:
x = np.array([np.nan, 0., np.inf])
any(~np.isfinite(x))

True

In [53]:
x = np.array([1, 0., 3])
assert not any(~np.isfinite(x))

In [5]:
a = np.array([1, 1, 5, 6, 1, 2, 2, 6, 1, 4])
stats.itemfreq(a)

array([[1, 4],
       [2, 2],
       [4, 1],
       [5, 1],
       [6, 2]], dtype=int64)

In [7]:
np.max(a)

6

In [6]:
np.bincount(a)

array([0, 4, 2, 0, 1, 1, 2], dtype=int64)

In [20]:
a[::-1]

array([2, 1])

In [28]:
[0]*1

[0]

In [29]:
[0]*0

[]

In [11]:
a = [1,7,3]
b = [3,4,5]
c = np.vstack((a, b))
c

array([[1, 7, 3],
       [3, 4, 5]])

In [15]:
d = np.argmax(c, axis=0)
d

array([1, 0, 1], dtype=int64)

In [17]:
d * 1/5 + d*1/2

array([ 0.7,  0. ,  0.7])

In [23]:
a = np.array([[6, 8, 3, 0],
...               [3, 2, 1, 7],
...               [4, 1, 8, 4],
...               [5, 3, 0, 5],
...               [4, 7, 5, 9]])
a

array([[6, 8, 3, 0],
       [3, 2, 1, 7],
       [4, 1, 8, 4],
       [5, 3, 0, 5],
       [4, 7, 5, 9]])

In [27]:
from scipy import stats
m = stats.mode(a, axis=1)
m

ModeResult(mode=array([[0],
       [1],
       [4],
       [5],
       [4]]), count=array([[1],
       [1],
       [2],
       [2],
       [1]]))

In [30]:
np.array([i[0] for i in m[0]])

array([0, 1, 4, 5, 4])

In [34]:
np.array([2]) * 3

array([6])

In [1]:
list = [["python", '1'],["python", '2'],["python", '3'],["python", '4']]

In [7]:
import pandas as pd

In [4]:
list_pd = pd.DataFrame(list)

In [6]:
list_pd.set_index(0).to_dict()

{1: {'python': '4'}}

In [8]:
import datetime
import time
ts = time.time()
datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')

'2017-12-07 11:04:24'

In [14]:
from enum import Enum, unique

@unique
class STATUS_FIT(Enum):
    STATUS_BREAK = "BREAK"
    STATUS_CONTINUE = "CONTINUE"
    STATUS_NOTPASS = "NOTPASS"
    MAX_LAYER = 100

In [15]:
STATUS_FIT.STATUS_NOTPASS

<STATUS_FIT.STATUS_NOTPASS: 'NOTPASS'>

In [1]:
for line in locals()['In']:
    print(line)


for line in locals()['In']:
    print(line)


In [2]:
history

for line in locals()['In']:
    print(line)
history


In [3]:
params = { 'objective': 'binary:logistic', 'num_class': 2 }

In [4]:
params

{'num_class': 2, 'objective': 'binary:logistic'}

In [8]:
import datetime
import time
with open("log.txt", "a") as f:
    tm = datetime.datetime.fromtimestamp(time.time()).strftime('%Y_%m_%d_%H_%M_%S.txt')
    f.write(tm+"-"+"prefix"+":"+"dsds"+"\n")

In [9]:
class LogRecord():

    def __init__(self):
        tm = datetime.datetime.fromtimestamp(time.time()).strftime('%Y_%m_%d_%H_%M_%S.txt')
        self.log_path = "./logs/" + tm

    def log(self, log_str, prefix=""):
        with open(self.log_path, "a") as f:
            tm = datetime.datetime.fromtimestamp(time.time()).strftime('%Y_%m_%d_%H_%M_%S')
            f.write(tm+"-"+prefix+":"+log_str+"\n")

    def log_array(self, array, prefix=""):
        log_str = np.array_str(array)
        self.log(log_str, prefix)

    def log_value(self, value, prefix=""):
        log_str = str(value)
        self.log(log_str, prefix)

In [10]:
LogRecord().log_array("hihihihi")

NameError: name 'np' is not defined

In [16]:
import numpy as np

In [17]:
a = np.array([True,False,True])

In [18]:
a[a==True].shape

(2,)

In [19]:
a==True

array([ True, False,  True], dtype=bool)

In [20]:
a[a==True]

array([ True,  True], dtype=bool)

In [21]:
a = np.array([1,2,3,4,5])

In [24]:
",".join([str(i) for i in a])

'1,2,3,4,5'