# 本文档是一个数据集读入和转化为列表的实验

## 实验对象是YEAST数据集

In [57]:
import os
import numpy as np
import pandas as pd
import time
import os.path as osp
import re
from sklearn.model_selection import train_test_split
from collections import Counter
np.set_printoptions(threshold=np.inf)

In [2]:
import DataHelper
import importlib
from collections import Counter
importlib.reload(DataHelper)

<module 'DataHelper' from 'C:\\Users\\dxeec\\Desktop\\EcoForest-master\\DataHelper.py'>

In [3]:
id2label = {}
label2id = {}

In [5]:
label_path = osp.abspath( osp.join(".\\datasetes", "yeast", "yeast.label") )

【osp.abspath】将当前绝对目录连接起来。
label是之前自己写好的数据。

In [7]:
with open(label_path) as f:
    for row in f:
        cols = row.strip().split(" ")
        id2label[int(cols[0])] = cols[1]
        label2id[cols[1]] = int(cols[0])

In [8]:
print(id2label)

{0: 'CYT', 1: 'NUC', 2: 'MIT', 3: 'ME3', 4: 'ME2', 5: 'ME1', 6: 'EXC', 7: 'VAC', 8: 'POX', 9: 'ERL'}


In [9]:
print(label2id)

{'CYT': 0, 'NUC': 1, 'MIT': 2, 'ME3': 3, 'ME2': 4, 'ME1': 5, 'EXC': 6, 'VAC': 7, 'POX': 8, 'ERL': 9}


In [11]:
data_path = osp.abspath( osp.join(".\\datasetes", "yeast", "yeast.data") )
with open(data_path) as f:
    rows = f.readlines()

In [13]:
n_datas = len(rows)

In [15]:
X = np.zeros((n_datas, 8), dtype=np.float32)
y = np.zeros(n_datas, dtype=np.int32)

In [32]:
for i, row in enumerate(rows):
    cols = re.split(" +", row.strip())
    #print(list(map(float, cols[1:1+8])))
    X[i,:] = list(map(float, cols[1:1+8]))
    y[i] = label2id[cols[-1]]

【enumerate()】 函数用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标，一般用在 for 循环当中。

【cols[-1]】就是取最后一个

In [33]:
train_idx, test_idx = train_test_split(range(n_datas), random_state=0, train_size=0.7, stratify=y)

C:\Users\dxeec\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


【train_test_split】
train_data：被划分的样本特征集；
train_target：被划分的样本标签；
test_size：如果是浮点数，在0-1之间，表示样本占比；如果是整数的话就是样本的数量；
random_state：是随机数的种子。

【range(n_datas)】是一个列表，[0,1484],相当于是只是划分了标号为训练集+测试集。

In [39]:
print("X.shape:", X[train_idx].shape, "y.shape:", y[train_idx].shape)
print("X.shape:", X[test_idx].shape, "y.shape:", y[test_idx].shape)

X.shape: (1038, 8) y.shape: (1038,)
X.shape: (446, 8) y.shape: (446,)


【X[train_idx]】高端用法，直接用列表train_idx来重排序列表X

最后return X[train_idx], y[train_idx], X[test_idx], y[test_idx]，将划分好的训练集数据集传回

In [52]:
Counter(y)

Counter({2: 244,
         1: 429,
         0: 463,
         5: 44,
         6: 35,
         4: 51,
         3: 163,
         7: 30,
         8: 20,
         9: 5})

【Counter】函数用来方便的统计类别信息，需要from collections import Counter。注意的是，只能对label的列表进行统计，不要对样本列表进行统计。

In [58]:
print(y)

[2 2 2 1 2 0 2 1 2 0 1 1 0 2 2 0 0 1 1 1 0 0 0 0 0 2 0 0 2 5 1 2 0 1 5 6 2
 0 2 2 4 4 4 3 7 1 4 6 7 3 0 3 1 0 0 0 0 0 0 2 2 1 1 1 0 0 0 0 0 6 0 0 2 2
 2 2 2 2 2 2 2 2 2 2 2 3 3 6 1 0 0 2 0 1 0 3 6 2 2 0 3 3 0 1 0 3 0 0 0 0 8
 1 1 1 1 2 2 2 2 2 2 2 2 2 3 2 1 2 1 0 0 0 0 1 1 0 3 1 0 1 0 1 1 1 0 1 0 0
 1 1 1 0 1 0 1 1 0 1 1 2 0 0 0 1 1 3 3 3 3 3 1 0 0 0 2 8 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 5 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 6 2 5 9 7 3
 1 0 0 1 1 1 4 8 1 1 3 6 6 0 0 0 2 2 2 2 2 0 0 0 2 2 3 3 8 1 1 1 7 1 1 1 1
 1 1 0 0 1 1 2 1 1 1 4 0 1 3 0 1 1 4 0 0 1 3 5 0 0 0 3 3 4 3 0 4 0 4 0 3 3
 3 0 4 0 3 4 1 1 9 6 0 0 0 0 0 0 0 0 3 3 3 1 6 8 8 0 5 1 3 5 4 0 0 0 3 0 3
 5 0 1 0 0 0 1 3 1 0 1 3 1 5 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 4 0 0 0 3 0 0
 0 0 0 1 0 1 3 0 4 0 0 0 0 1 0 1 1 0 0 1 2 0 1 1 1 1 0 1 1 2 0 0 2 0 0 1 1
 1 1 1 3 1 1 0 3 3 1 1 1 1 1 1 1 3 5 1 0 1 2 0 0 3 2 2 0 1 1 1 1 2 0 0 3 3
 3 3 3 3 3 3 8 2 2 0 2 2 0 2 2 2 1 2 2 2 0 1 1 0 3 3 5 2 2 3 3 1 3 4 1 2 3
 3 5 4 3 3 0 1 9 1 1 5 5 

In [59]:
print(X[train_idx])

[[0.51 0.49 0.48 0.55 0.5  0.   0.52 0.58]
 [0.78 0.65 0.4  0.16 0.5  0.   0.63 0.22]
 [0.59 0.64 0.44 0.26 0.5  0.   0.5  0.22]
 [0.4  0.45 0.42 0.17 0.5  0.   0.54 0.26]
 [0.6  0.48 0.46 0.32 0.5  0.   0.4  0.33]
 [0.45 0.45 0.52 0.17 0.5  0.   0.54 0.22]
 [0.47 0.38 0.58 0.19 0.5  0.   0.57 0.22]
 [0.56 0.35 0.47 0.41 0.5  0.   0.5  0.22]
 [0.24 0.41 0.47 0.16 0.5  0.   0.51 0.38]
 [0.59 0.53 0.43 0.44 0.5  0.   0.5  0.22]
 [0.5  0.34 0.55 0.21 0.5  0.   0.49 0.22]
 [0.36 0.37 0.63 0.25 0.5  0.   0.3  0.22]
 [0.58 0.58 0.58 0.49 0.5  0.   0.49 0.26]
 [0.4  0.45 0.61 0.29 0.5  0.   0.44 0.22]
 [0.66 0.54 0.53 0.17 0.5  0.   0.54 0.22]
 [0.46 0.53 0.47 0.37 0.5  0.   0.51 0.36]
 [0.63 0.56 0.45 0.58 0.5  0.   0.51 0.22]
 [0.49 0.51 0.52 0.13 0.5  0.   0.51 0.33]
 [0.63 0.56 0.52 0.21 0.5  0.   0.5  0.22]
 [0.58 0.51 0.49 0.27 0.5  0.   0.57 0.29]
 [0.85 0.66 0.49 0.18 0.5  0.   0.51 0.22]
 [0.42 0.21 0.59 0.3  0.5  0.   0.47 0.27]
 [0.49 0.31 0.43 0.24 0.5  0.   0.54 0.22]
 [0.8  0.79